Nedlasting av public key trenger ikke autentisering
ks-no/fiks-io-client-dotnet pull request #174
Opened 2023-10-02 08:57 UTC by zapodot

2023-10-02 10:41 UTC, jarleborsheim requested changes
Se kommentar

2023-10-02 10:41 UTC, jarleborsheim commented on KS.Fiks.IO.Client/Catalog/CatalogHandler.cs
> +            var responseAsPublicKeyModel = await GetAsModel<KontoOffentligNokkel>(requestUri, authenticated: false).ConfigureAwait(false);
Usikker på om parameternavnet "authenticated" er litt missvisende? Er det ikke bedre med "authenticate"? At vi ber om å autentisere?

2023-10-02 14:07 UTC, zapodot commented on KS.Fiks.IO.Client/Catalog/CatalogHandler.cs
> +            var responseAsPublicKeyModel = await GetAsModel<KontoOffentligNokkel>(requestUri, authenticated: false).ConfigureAwait(false);
Usikker på jeg er enig i det. Jeg leser det som om man ønsker å ha med autentisering eller ikke

2023-10-03 08:29 UTC, jarleborsheim commented on KS.Fiks.IO.Client/Catalog/CatalogHandler.cs
> +            var responseAsPublicKeyModel = await GetAsModel<KontoOffentligNokkel>(requestUri, authenticated: false).ConfigureAwait(false);
Har ikke noen sterk formening om det. Blir smak og behag. La det være. 👍

2023-10-03 08:29 UTC, jarleborsheim approved these changes
LGTM 👍

2023-10-03 09:14 UTC, merged